import React, { useRef, useEffect, useState } from 'react';

/**
 * ShareableCard - Canvas-rendered preview of the IG Story card
 * Shows a smaller preview; the full-size PNG is generated by shareUtils
 */
export default function ShareableCard({
  name,
  photoUrl,
  handle,
  competitionTitle,
  cityName,
  season,
  quote,
  accentColor = '#d4af37',
  isNomination = false,
}) {
  const canvasRef = useRef(null);
  const [imageLoaded, setImageLoaded] = useState(false);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    const ctx = canvas.getContext('2d');
    const w = canvas.width;
    const h = canvas.height;
    const scale = w / 1080;

    // Background
    const bgGrad = ctx.createLinearGradient(0, 0, 0, h);
    bgGrad.addColorStop(0, '#0a0a0c');
    bgGrad.addColorStop(0.5, '#111114');
    bgGrad.addColorStop(1, '#0a0a0c');
    ctx.fillStyle = bgGrad;
    ctx.fillRect(0, 0, w, h);

    // Accent glow
    const glowGrad = ctx.createRadialGradient(
      w / 2, h * 0.35, 0,
      w / 2, h * 0.35, 250 * scale
    );
    glowGrad.addColorStop(0, `${accentColor}15`);
    glowGrad.addColorStop(1, 'transparent');
    ctx.fillStyle = glowGrad;
    ctx.fillRect(0, 0, w, h);

    const cx = w / 2;
    let y = 140 * scale;

    // Branding
    ctx.fillStyle = accentColor;
    ctx.font = `bold ${18 * scale}px -apple-system, BlinkMacSystemFont, sans-serif`;
    ctx.textAlign = 'center';
    ctx.fillText('ELITERANK', cx, y);
    y += 30 * scale;

    // Competition title
    ctx.fillStyle = '#a1a1aa';
    ctx.font = `500 ${14 * scale}px -apple-system, BlinkMacSystemFont, sans-serif`;
    ctx.fillText(competitionTitle || 'Competition', cx, y);
    y += 50 * scale;

    // Photo circle
    const photoR = 75 * scale;
    const photoCY = y + photoR;

    if (photoUrl && imageLoaded) {
      const img = new Image();
      img.crossOrigin = 'anonymous';
      img.onload = () => {
        ctx.save();
        ctx.beginPath();
        ctx.arc(cx, photoCY, photoR, 0, Math.PI * 2);
        ctx.clip();
        ctx.drawImage(img, cx - photoR, photoCY - photoR, photoR * 2, photoR * 2);
        ctx.restore();

        // Ring
        ctx.strokeStyle = accentColor;
        ctx.lineWidth = 2;
        ctx.beginPath();
        ctx.arc(cx, photoCY, photoR + 2, 0, Math.PI * 2);
        ctx.stroke();

        drawRest();
      };
      img.onerror = () => {
        drawInitialCircle();
        drawRest();
      };
      img.src = photoUrl;
    } else {
      drawInitialCircle();
      drawRest();
    }

    function drawInitialCircle() {
      const gradient = ctx.createLinearGradient(
        cx - photoR, photoCY - photoR,
        cx + photoR, photoCY + photoR
      );
      gradient.addColorStop(0, accentColor);
      gradient.addColorStop(1, '#1c1c1f');
      ctx.beginPath();
      ctx.arc(cx, photoCY, photoR, 0, Math.PI * 2);
      ctx.fillStyle = gradient;
      ctx.fill();

      ctx.fillStyle = '#ffffff';
      ctx.font = `bold ${photoR * 0.8}px -apple-system, BlinkMacSystemFont, sans-serif`;
      ctx.textAlign = 'center';
      ctx.textBaseline = 'middle';
      ctx.fillText((name?.charAt(0) || '?').toUpperCase(), cx, photoCY);
      ctx.textBaseline = 'alphabetic';

      // Ring
      ctx.strokeStyle = accentColor;
      ctx.lineWidth = 2;
      ctx.beginPath();
      ctx.arc(cx, photoCY, photoR + 2, 0, Math.PI * 2);
      ctx.stroke();
    }

    function drawRest() {
      let ry = photoCY + photoR + 28 * scale;

      // Name
      ctx.fillStyle = '#ffffff';
      ctx.font = `bold ${28 * scale}px -apple-system, BlinkMacSystemFont, sans-serif`;
      ctx.textAlign = 'center';
      ctx.fillText(name || 'Nominee', cx, ry);
      ry += 24 * scale;

      // Handle / City
      const parts = [];
      if (handle) parts.push(`@${handle.replace('@', '')}`);
      if (cityName) parts.push(cityName);
      if (parts.length) {
        ctx.fillStyle = '#a1a1aa';
        ctx.font = `400 ${14 * scale}px -apple-system, BlinkMacSystemFont, sans-serif`;
        ctx.fillText(parts.join('  •  '), cx, ry);
      }
      ry += 28 * scale;

      // Pill
      const pillText = isNomination ? 'NOMINATED' : 'ENTERED';
      ctx.font = `bold ${12 * scale}px -apple-system, BlinkMacSystemFont, sans-serif`;
      const pw = ctx.measureText(pillText).width + 24 * scale;
      const ph = 22 * scale;

      ctx.beginPath();
      const pr = ph / 2;
      ctx.moveTo(cx - pw / 2 + pr, ry - ph / 2);
      ctx.lineTo(cx + pw / 2 - pr, ry - ph / 2);
      ctx.quadraticCurveTo(cx + pw / 2, ry - ph / 2, cx + pw / 2, ry);
      ctx.quadraticCurveTo(cx + pw / 2, ry + ph / 2, cx + pw / 2 - pr, ry + ph / 2);
      ctx.lineTo(cx - pw / 2 + pr, ry + ph / 2);
      ctx.quadraticCurveTo(cx - pw / 2, ry + ph / 2, cx - pw / 2, ry);
      ctx.quadraticCurveTo(cx - pw / 2, ry - ph / 2, cx - pw / 2 + pr, ry - ph / 2);
      ctx.closePath();
      ctx.fillStyle = `${accentColor}30`;
      ctx.fill();
      ctx.strokeStyle = accentColor;
      ctx.lineWidth = 1;
      ctx.stroke();

      ctx.fillStyle = accentColor;
      ctx.textAlign = 'center';
      ctx.textBaseline = 'middle';
      ctx.fillText(pillText, cx, ry);
      ctx.textBaseline = 'alphabetic';
      ry += ph / 2 + 24 * scale;

      // Quote
      if (quote) {
        ctx.fillStyle = '#e4e4e7';
        ctx.font = `italic ${13 * scale}px -apple-system, BlinkMacSystemFont, sans-serif`;
        const maxW = (w - 140 * scale);
        const words = quote.split(' ');
        let line = '';
        const lines = [];
        for (const word of words) {
          const test = line ? `${line} ${word}` : word;
          if (ctx.measureText(test).width > maxW) {
            lines.push(line);
            line = word;
          } else {
            line = test;
          }
        }
        if (line) lines.push(line);
        for (const l of lines.slice(0, 2)) {
          ctx.fillText(l, cx, ry);
          ry += 18 * scale;
        }
      }
    }
  }, [name, photoUrl, handle, competitionTitle, cityName, season, quote, accentColor, isNomination, imageLoaded]);

  // Pre-load photo
  useEffect(() => {
    if (!photoUrl) return;
    const img = new Image();
    img.crossOrigin = 'anonymous';
    img.onload = () => setImageLoaded(true);
    img.src = photoUrl;
  }, [photoUrl]);

  return (
    <div className="entry-shareable-card">
      <canvas
        ref={canvasRef}
        width={360}
        height={640}
        className="entry-card-canvas"
      />
    </div>
  );
}
