import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

/**
 * subscriber-unsubscribe — One-click unsubscribe endpoint for users who
 * opted in on a competition's coming-soon page.
 *
 * GET /subscriber-unsubscribe?token=<subscriber_id>.<hmac_hex>
 *
 * The token is an HMAC-SHA256(subscriber_id) signature, generated by
 * send-onesignal-email at send time. Verifying the signature authenticates
 * the request without requiring login — the whole point of a one-click
 * email unsubscribe.
 *
 * Deletes the matching competition_subscribers row and renders a branded
 * HTML confirmation page. Idempotent: clicking twice is fine.
 *
 * Required Supabase secrets:
 *   SUPABASE_URL                       — Supabase project URL
 *   SUPABASE_SERVICE_ROLE_KEY          — needed to delete rows without a JWT
 *   SUBSCRIBER_UNSUBSCRIBE_SECRET      — HMAC secret. Falls back to
 *                                        FAN_UNSUBSCRIBE_SECRET if not set,
 *                                        so the system works on day one.
 *   APP_URL                            — e.g. https://eliterank.co
 */

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

async function hmacHex(message: string, secret: string): Promise<string> {
  const key = await crypto.subtle.importKey(
    'raw',
    new TextEncoder().encode(secret),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign'],
  )
  const sig = await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(message))
  return Array.from(new Uint8Array(sig))
    .map(b => b.toString(16).padStart(2, '0'))
    .join('')
}

function constantTimeEqual(a: string, b: string): boolean {
  if (a.length !== b.length) return false
  let diff = 0
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i)
  return diff === 0
}

async function verifyToken(token: string | null, secret: string): Promise<string | null> {
  if (!token) return null
  const dot = token.indexOf('.')
  if (dot <= 0 || dot === token.length - 1) return null
  const subscriberId = token.slice(0, dot)
  const sig = token.slice(dot + 1)
  const expected = await hmacHex(subscriberId, secret)
  return constantTimeEqual(sig, expected) ? subscriberId : null
}

function htmlResponse(body: string, status = 200): Response {
  const bytes = new TextEncoder().encode(body)
  const headers = new Headers({
    'Content-Type': 'text/html; charset=utf-8',
    'Content-Length': String(bytes.byteLength),
    'Cache-Control': 'no-store',
    'X-Content-Type-Options': 'nosniff',
  })
  for (const [k, v] of Object.entries(corsHeaders)) headers.set(k, v)
  return new Response(bytes, { status, headers })
}

function renderPage(args: {
  appUrl: string
  title: string
  heading: string
  message: string
  ctaLabel?: string
  ctaUrl?: string
}): string {
  const { appUrl, title, heading, message, ctaLabel, ctaUrl } = args
  const cta = ctaLabel && ctaUrl
    ? `<div style="text-align:center;margin:24px 0;">
         <a href="${ctaUrl}" style="display:inline-block;padding:14px 32px;background:linear-gradient(135deg,#d4a843,#f4d03f);color:#000;text-decoration:none;border-radius:8px;font-weight:bold;font-size:16px;">${ctaLabel}</a>
       </div>`
    : ''
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>${title} &mdash; EliteRank</title>
</head>
<body style="margin:0;padding:0;background:#0a0a0a;color:#fff;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
  <div style="max-width:480px;margin:0 auto;padding:16px;">
    <div style="text-align:center;padding:32px 0 16px;">
      <span style="font-size:12px;letter-spacing:0.3em;color:#999;">ELITERANK</span>
    </div>
    <div style="text-align:center;padding:24px;">
      <h1 style="color:#d4a843;font-size:26px;margin:0 0 12px;">${heading}</h1>
      <p style="color:#ccc;font-size:15px;line-height:1.5;margin:0 0 16px;">${message}</p>
      ${cta}
    </div>
    <div style="text-align:center;padding:24px 0;border-top:1px solid #333;margin-top:32px;">
      <a href="${appUrl}" style="color:#d4a843;font-size:12px;text-decoration:none;">eliterank.co</a>
    </div>
  </div>
</body>
</html>`
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  const appUrl = Deno.env.get('APP_URL') || 'https://eliterank.co'
  const secret = Deno.env.get('SUBSCRIBER_UNSUBSCRIBE_SECRET') || Deno.env.get('FAN_UNSUBSCRIBE_SECRET')
  const supabaseUrl = Deno.env.get('SUPABASE_URL')
  const serviceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')

  if (!secret || !supabaseUrl || !serviceKey) {
    console.error('subscriber-unsubscribe: missing env vars')
    return htmlResponse(renderPage({
      appUrl,
      title: 'Error',
      heading: 'Something went wrong',
      message: 'We could not process this unsubscribe link right now. Please try again later.',
    }), 503)
  }

  const url = new URL(req.url)
  const token = url.searchParams.get('token')

  const subscriberId = await verifyToken(token, secret)
  if (!subscriberId) {
    return htmlResponse(renderPage({
      appUrl,
      title: 'Invalid link',
      heading: 'Link expired or invalid',
      message: 'This unsubscribe link could not be verified. You can manage your email preferences after logging in.',
      ctaLabel: 'Go to EliteRank',
      ctaUrl: appUrl,
    }), 400)
  }

  const supabase = createClient(supabaseUrl, serviceKey, {
    auth: { autoRefreshToken: false, persistSession: false },
  })

  // Look up the competition name BEFORE deleting so the confirmation page
  // can name what they unsubscribed from. If the row is already gone (user
  // clicked twice) we still respond with success.
  const { data: subRow } = await supabase
    .from('competition_subscribers')
    .select('competition:competitions(name)')
    .eq('id', subscriberId)
    .maybeSingle()

  const competitionName = (subRow as { competition?: { name?: string } } | null)?.competition?.name || 'this competition'

  const { error: deleteErr } = await supabase
    .from('competition_subscribers')
    .delete()
    .eq('id', subscriberId)

  if (deleteErr) {
    console.error('subscriber-unsubscribe: delete failed', deleteErr)
    return htmlResponse(renderPage({
      appUrl,
      title: 'Error',
      heading: 'Something went wrong',
      message: 'We could not update your preferences right now. Please try again later.',
      ctaLabel: 'Go to EliteRank',
      ctaUrl: appUrl,
    }), 500)
  }

  return htmlResponse(renderPage({
    appUrl,
    title: 'Unsubscribed',
    heading: "You've been unsubscribed",
    message: `You will no longer receive email updates about <strong style="color:#fff;">${competitionName}</strong>.`,
    ctaLabel: 'Go to EliteRank',
    ctaUrl: appUrl,
  }))
})
