import React, { useState, useMemo, useRef } from 'react';
import {
  Building2, ChevronLeft, Upload, X, Trophy, Plus,
} from 'lucide-react';
import { Button } from '@shared/components/ui';
import { colors, spacing, borderRadius, typography, transitions } from '@shared/styles/theme';
import { supabase } from '@shared/lib/supabase';
import FormModal from '../../../components/FormModal';
import {
  FormField, TextInput, SelectInput, FormGrid, FormSection,
} from '../../../components/FormField';
import { generateCompetitionSlug, getCompetitionUrl } from '@shared/utils/slugs';

const WIZARD_STEPS = [
  { id: 1, name: 'Organization', description: 'Select organization' },
  { id: 2, name: 'Details', description: 'Name, city & season' },
  { id: 3, name: 'Winners', description: 'Add past winners' },
  { id: 4, name: 'Review', description: 'Confirm & create' },
];

const INITIAL_FORM = {
  organization_id: '',
  city_id: '',
  category_id: '',
  demographic_id: '',
  name: '',
  season: new Date().getFullYear(),
  number_of_winners: 5,
  cover_image: '',
};

/**
 * Wizard for creating a legacy/historical competition record
 * for competitions that were hosted outside of EliteRank.
 */
export default function LegacyCompetitionWizard({
  isOpen,
  onClose,
  onCreate,
  loading,
  organizations,
  cities,
  categories,
  demographics,
}) {
  const [currentStep, setCurrentStep] = useState(1);
  const [formData, setFormData] = useState(INITIAL_FORM);
  const [winners, setWinners] = useState([]);

  const resetAndClose = () => {
    setFormData(INITIAL_FORM);
    setWinners([]);
    setCurrentStep(1);
    onClose();
  };

  const updateField = (field, value) => {
    setFormData(prev => ({ ...prev, [field]: value }));
  };

  const seasonOptions = useMemo(() => {
    const years = [];
    for (let y = new Date().getFullYear(); y >= 2018; y--) {
      years.push({ value: String(y), label: String(y) });
    }
    return years;
  }, []);

  const cityOptions = useMemo(() =>
    cities.map(c => ({ value: c.id, label: `${c.name}, ${c.state}` })),
    [cities],
  );

  const categoryOptions = useMemo(() =>
    categories.map(c => ({ value: c.id, label: c.name })),
    [categories],
  );

  const demographicOptions = useMemo(() =>
    demographics.map(d => ({ value: d.id, label: d.label })),
    [demographics],
  );

  const autoGeneratedName = useMemo(() => {
    const org = organizations.find(o => o.id === formData.organization_id);
    const city = cities.find(c => c.id === formData.city_id);
    const demo = demographics.find(d => d.id === formData.demographic_id);
    if (!org || !city) return '';
    const isOpen = !demo || demo.slug === 'open';
    return isOpen ? `${org.name} ${city.name}` : `${org.name} ${city.name} - ${demo.label}`;
  }, [formData.organization_id, formData.city_id, formData.demographic_id, organizations, cities, demographics]);

  const canAdvance = useMemo(() => {
    if (currentStep === 1) return !!formData.organization_id;
    if (currentStep === 2) return !!(formData.city_id && formData.category_id && formData.demographic_id);
    return true;
  }, [currentStep, formData]);

  const canCreate = !!(formData.organization_id && formData.city_id && formData.category_id && formData.demographic_id);

  const handleSubmit = () => {
    if (currentStep < WIZARD_STEPS.length) {
      if (!canAdvance) return;
      setCurrentStep(prev => prev + 1);
    } else {
      if (!canCreate) return;
      onCreate({ ...formData, winners });
    }
  };

  const submitLabel = currentStep < WIZARD_STEPS.length
    ? 'Next'
    : loading ? 'Creating...' : 'Create Legacy Competition';

  const stepIndicator = (
    <div style={styles.stepBar}>
      {WIZARD_STEPS.map((step, index) => (
        <div key={step.id} style={styles.stepItem}>
          <div style={{
            ...styles.stepCircle,
            background: currentStep >= step.id ? colors.gold.primary : colors.background.elevated,
            color: currentStep >= step.id ? colors.text.inverse : colors.text.tertiary,
          }}>
            {step.id}
          </div>
          {index < WIZARD_STEPS.length - 1 && (
            <div style={{
              ...styles.stepLine,
              background: currentStep > step.id ? colors.gold.primary : colors.border.secondary,
            }} />
          )}
        </div>
      ))}
    </div>
  );

  return (
    <FormModal
      isOpen={isOpen}
      onClose={resetAndClose}
      title="Add Past Competition"
      subtitle={`Step ${currentStep} of ${WIZARD_STEPS.length}: ${WIZARD_STEPS[currentStep - 1].description}`}
      onSubmit={handleSubmit}
      submitLabel={submitLabel}
      loading={loading}
      size="lg"
    >
      {stepIndicator}

      {/* Step 1: Organization */}
      {currentStep === 1 && (
        <FormSection title="Select Organization" divider={false}>
          <div style={styles.orgList}>
            {organizations.map(org => (
              <button
                key={org.id}
                type="button"
                onClick={() => updateField('organization_id', org.id)}
                style={{
                  ...styles.orgCard,
                  borderColor: formData.organization_id === org.id ? colors.gold.primary : colors.border.primary,
                  background: formData.organization_id === org.id ? colors.gold.muted : colors.background.tertiary,
                }}
              >
                {org.logo_url ? (
                  <img src={org.logo_url} alt={org.name} style={styles.orgLogo} />
                ) : (
                  <div style={styles.orgLogoPlaceholder}>
                    <Building2 size={18} style={{ color: colors.text.tertiary }} />
                  </div>
                )}
                <div style={{ minWidth: 0 }}>
                  <p style={{ fontWeight: typography.fontWeight.medium, color: colors.text.primary, fontSize: typography.fontSize.sm }}>
                    {org.name}
                  </p>
                </div>
              </button>
            ))}
          </div>
        </FormSection>
      )}

      {/* Step 2: Details */}
      {currentStep === 2 && (
        <FormSection title="Competition Details" divider={false}>
          <FormGrid>
            <FormField label="City" required>
              <SelectInput
                value={formData.city_id}
                onChange={(e) => updateField('city_id', e.target.value)}
                options={cityOptions}
                placeholder="Select a city..."
              />
            </FormField>
            <FormField label="Season Year" required>
              <SelectInput
                value={String(formData.season)}
                onChange={(e) => updateField('season', parseInt(e.target.value))}
                options={seasonOptions}
              />
            </FormField>
          </FormGrid>
          <FormGrid>
            <FormField label="Category" required>
              <SelectInput
                value={formData.category_id}
                onChange={(e) => updateField('category_id', e.target.value)}
                options={categoryOptions}
                placeholder="Select a category..."
              />
            </FormField>
            <FormField label="Demographic" required>
              <SelectInput
                value={formData.demographic_id}
                onChange={(e) => updateField('demographic_id', e.target.value)}
                options={demographicOptions}
                placeholder="Select a demographic..."
              />
            </FormField>
          </FormGrid>
          <FormField
            label="Competition Name"
            description={formData.name
              ? 'Using custom name'
              : autoGeneratedName
                ? `Will auto-generate as: "${autoGeneratedName}"`
                : 'Leave blank to auto-generate'}
          >
            <TextInput
              value={formData.name}
              onChange={(e) => updateField('name', e.target.value)}
              placeholder={autoGeneratedName || 'e.g., Most Eligible Miami'}
            />
          </FormField>
        </FormSection>
      )}

      {/* Step 3: Winners */}
      {currentStep === 3 && (
        <FormSection title="Past Winners" divider={false}>
          <p style={{ fontSize: typography.fontSize.sm, color: colors.text.tertiary, margin: `0 0 ${spacing.md}` }}>
            Add the winners from this past competition. Photos can be uploaded or left blank.
          </p>
          <WinnersEditor winners={winners} onChange={setWinners} />
        </FormSection>
      )}

      {/* Step 4: Review */}
      {currentStep === 4 && (
        <LegacyReviewStep
          formData={formData}
          winners={winners}
          organizations={organizations}
          cities={cities}
          categories={categories}
          demographics={demographics}
        />
      )}

      {currentStep > 1 && (
        <div style={styles.backButtonRow}>
          <Button
            variant="secondary"
            size="sm"
            icon={ChevronLeft}
            onClick={() => setCurrentStep(prev => Math.max(1, prev - 1))}
            type="button"
          >
            Back
          </Button>
        </div>
      )}
    </FormModal>
  );
}


/**
 * Inline winners editor for adding name + photo for each winner.
 */
function WinnersEditor({ winners, onChange }) {
  const addWinner = () => {
    onChange([...winners, { name: '', imageUrl: '', rank: winners.length + 1 }]);
  };

  const updateWinner = (index, field, value) => {
    const updated = [...winners];
    updated[index] = { ...updated[index], [field]: value };
    onChange(updated);
  };

  const removeWinner = (index) => {
    const updated = winners.filter((_, i) => i !== index);
    // Re-rank
    onChange(updated.map((w, i) => ({ ...w, rank: i + 1 })));
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: spacing.md }}>
      {winners.map((winner, index) => (
        <WinnerRow
          key={index}
          winner={winner}
          index={index}
          onUpdate={(field, value) => updateWinner(index, field, value)}
          onRemove={() => removeWinner(index)}
        />
      ))}
      <button
        type="button"
        onClick={addWinner}
        style={styles.addWinnerBtn}
      >
        <Plus size={16} />
        <span>Add Winner</span>
      </button>
    </div>
  );
}


function WinnerRow({ winner, index, onUpdate, onRemove }) {
  const fileInputRef = useRef(null);
  const [uploading, setUploading] = useState(false);

  const handleFileSelect = async (e) => {
    const file = e.target.files?.[0];
    if (!file) return;
    if (!file.type.startsWith('image/')) return;
    if (file.size > 4.5 * 1024 * 1024) {
      alert('Photo must be under 4.5MB');
      return;
    }

    setUploading(true);
    try {
      const ext = file.name.split('.').pop()?.toLowerCase() || 'jpg';
      const fileName = `legacy-winners/${Date.now()}-${Math.random().toString(36).substring(2, 9)}.${ext}`;

      const { error } = await supabase.storage
        .from('avatars')
        .upload(fileName, file, { cacheControl: '3600', upsert: false });

      if (error) throw error;

      const { data: urlData } = supabase.storage
        .from('avatars')
        .getPublicUrl(fileName);

      onUpdate('imageUrl', urlData.publicUrl);
    } catch (err) {
      console.error('Upload failed:', err);
      alert('Upload failed. Please try again.');
    } finally {
      setUploading(false);
      if (fileInputRef.current) fileInputRef.current.value = '';
    }
  };

  return (
    <div style={styles.winnerRow}>
      <div style={styles.winnerRank}>{index + 1}</div>

      {/* Photo */}
      <div style={styles.winnerPhotoArea}>
        {winner.imageUrl ? (
          <div style={styles.winnerPhotoPreview}>
            <img src={winner.imageUrl} alt={winner.name} style={styles.winnerPhotoImg} />
            <button
              type="button"
              onClick={() => onUpdate('imageUrl', '')}
              style={styles.winnerPhotoRemove}
            >
              <X size={12} />
            </button>
          </div>
        ) : (
          <button
            type="button"
            onClick={() => fileInputRef.current?.click()}
            disabled={uploading}
            style={styles.winnerPhotoUpload}
          >
            {uploading ? (
              <span style={{ fontSize: typography.fontSize.xs, color: colors.text.tertiary }}>...</span>
            ) : (
              <Upload size={16} style={{ color: colors.text.tertiary }} />
            )}
          </button>
        )}
        <input
          ref={fileInputRef}
          type="file"
          accept="image/*"
          onChange={handleFileSelect}
          style={{ display: 'none' }}
        />
      </div>

      {/* Name */}
      <input
        type="text"
        value={winner.name}
        onChange={(e) => onUpdate('name', e.target.value)}
        placeholder={`Winner #${index + 1} name`}
        style={styles.winnerNameInput}
      />

      {/* Remove */}
      <button type="button" onClick={onRemove} style={styles.winnerRemoveBtn}>
        <X size={14} />
      </button>
    </div>
  );
}


function LegacyReviewStep({ formData, winners, organizations, cities, categories, demographics }) {
  const selectedOrg = organizations.find(o => o.id === formData.organization_id);
  const selectedCity = cities.find(c => c.id === formData.city_id);
  const selectedCategory = categories.find(c => c.id === formData.category_id);
  const selectedDemographic = demographics.find(d => d.id === formData.demographic_id);
  const isOpenDemographic = selectedDemographic?.slug === 'open';

  const displayName = formData.name
    ? formData.name
    : selectedOrg && selectedCity
      ? isOpenDemographic || !selectedDemographic
        ? `${selectedOrg.name} ${selectedCity.name}`
        : `${selectedOrg.name} ${selectedCity.name} - ${selectedDemographic.label}`
      : 'Auto-generated';

  const rows = [
    { label: 'Organization', value: selectedOrg?.name || 'Not selected' },
    { label: 'Competition Name', value: displayName },
    { label: 'Location', value: selectedCity ? `${selectedCity.name}, ${selectedCity.state}` : 'Not selected' },
    { label: 'Category', value: selectedCategory?.name || 'Not selected' },
    { label: 'Demographic', value: selectedDemographic?.label || 'Not selected' },
    { label: 'Season', value: formData.season },
    { label: 'Winners', value: `${winners.filter(w => w.name).length} added` },
    { label: 'Status', value: 'Completed (Legacy)' },
  ];

  return (
    <FormSection title="Review" divider={false}>
      <div style={styles.reviewGrid}>
        {rows.map(row => (
          <div key={row.label} style={styles.reviewRow}>
            <span style={styles.reviewLabel}>{row.label}</span>
            <span style={styles.reviewValue}>{row.value}</span>
          </div>
        ))}
      </div>

      {winners.length > 0 && (
        <div style={{ marginTop: spacing.md }}>
          <p style={{ fontSize: typography.fontSize.xs, color: colors.text.tertiary, textTransform: 'uppercase', letterSpacing: '1px', marginBottom: spacing.sm }}>
            Winners Preview
          </p>
          <div style={{ display: 'flex', gap: spacing.md, flexWrap: 'wrap' }}>
            {winners.filter(w => w.name).map((w, i) => (
              <div key={i} style={{ display: 'flex', alignItems: 'center', gap: spacing.sm, padding: spacing.sm, background: colors.background.tertiary, borderRadius: borderRadius.md }}>
                {w.imageUrl ? (
                  <img src={w.imageUrl} alt={w.name} style={{ width: 28, height: 28, borderRadius: borderRadius.full, objectFit: 'cover' }} />
                ) : (
                  <div style={{ width: 28, height: 28, borderRadius: borderRadius.full, background: colors.background.elevated, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                    <Trophy size={12} style={{ color: colors.text.tertiary }} />
                  </div>
                )}
                <span style={{ fontSize: typography.fontSize.sm, color: colors.text.primary }}>{w.name}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      <p style={styles.footerNote}>
        This will create a completed competition record visible on the Explore page.
      </p>
    </FormSection>
  );
}


const styles = {
  stepBar: {
    display: 'flex',
    alignItems: 'center',
    gap: spacing[1],
    marginBottom: spacing.xl,
    padding: `${spacing.md} 0`,
    borderBottom: `1px solid ${colors.border.secondary}`,
  },
  stepItem: {
    display: 'flex',
    alignItems: 'center',
    flex: 1,
    gap: spacing[1],
  },
  stepCircle: {
    width: '24px',
    height: '24px',
    borderRadius: borderRadius.full,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: typography.fontSize.xs,
    fontWeight: typography.fontWeight.bold,
    flexShrink: 0,
  },
  stepLine: {
    flex: 1,
    height: '2px',
    borderRadius: '1px',
  },
  orgList: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.sm,
  },
  orgCard: {
    display: 'flex',
    alignItems: 'center',
    gap: spacing.md,
    padding: spacing.md,
    border: `1px solid ${colors.border.primary}`,
    borderRadius: borderRadius.md,
    cursor: 'pointer',
    textAlign: 'left',
    width: '100%',
    fontFamily: typography.fontFamily.sans,
    transition: transitions.colors,
  },
  orgLogo: {
    width: 36,
    height: 36,
    borderRadius: borderRadius.md,
    objectFit: 'cover',
    flexShrink: 0,
  },
  orgLogoPlaceholder: {
    width: 36,
    height: 36,
    borderRadius: borderRadius.md,
    background: colors.background.elevated,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  // Winners editor
  addWinnerBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    padding: spacing.md,
    background: 'transparent',
    border: `2px dashed ${colors.border.secondary}`,
    borderRadius: borderRadius.md,
    color: colors.text.secondary,
    cursor: 'pointer',
    fontSize: typography.fontSize.sm,
    fontFamily: typography.fontFamily.sans,
    transition: transitions.colors,
  },
  winnerRow: {
    display: 'flex',
    alignItems: 'center',
    gap: spacing.md,
    padding: spacing.md,
    background: colors.background.tertiary,
    borderRadius: borderRadius.md,
  },
  winnerRank: {
    width: 24,
    height: 24,
    borderRadius: borderRadius.full,
    background: colors.gold.muted,
    color: colors.gold.primary,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: typography.fontSize.xs,
    fontWeight: typography.fontWeight.bold,
    flexShrink: 0,
  },
  winnerPhotoArea: {
    flexShrink: 0,
  },
  winnerPhotoPreview: {
    position: 'relative',
    width: 44,
    height: 44,
  },
  winnerPhotoImg: {
    width: 44,
    height: 44,
    borderRadius: borderRadius.full,
    objectFit: 'cover',
  },
  winnerPhotoRemove: {
    position: 'absolute',
    top: -4,
    right: -4,
    width: 18,
    height: 18,
    borderRadius: borderRadius.full,
    background: colors.status.error,
    border: 'none',
    color: '#fff',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
  },
  winnerPhotoUpload: {
    width: 44,
    height: 44,
    borderRadius: borderRadius.full,
    background: colors.background.elevated,
    border: `1px dashed ${colors.border.secondary}`,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
  },
  winnerNameInput: {
    flex: 1,
    height: 36,
    padding: `0 ${spacing.md}`,
    background: colors.background.secondary,
    border: `1px solid ${colors.border.primary}`,
    borderRadius: borderRadius.md,
    color: colors.text.primary,
    fontSize: typography.fontSize.sm,
    fontFamily: typography.fontFamily.sans,
    outline: 'none',
  },
  winnerRemoveBtn: {
    background: 'transparent',
    border: 'none',
    color: colors.text.tertiary,
    cursor: 'pointer',
    padding: spacing.xs,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  // Review
  reviewGrid: {
    background: colors.background.tertiary,
    borderRadius: borderRadius.md,
    padding: spacing.md,
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.sm,
  },
  reviewRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: `${spacing[1]} 0`,
    borderBottom: `1px solid ${colors.border.secondary}`,
  },
  reviewLabel: {
    fontSize: typography.fontSize.xs,
    color: colors.text.tertiary,
    textTransform: 'uppercase',
    letterSpacing: typography.letterSpacing.wide,
  },
  reviewValue: {
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.medium,
    color: colors.text.primary,
  },
  footerNote: {
    fontSize: typography.fontSize.xs,
    color: colors.text.tertiary,
    textAlign: 'center',
    margin: 0,
    marginTop: spacing.md,
  },
  backButtonRow: {
    marginTop: spacing.lg,
    paddingTop: spacing.md,
    borderTop: `1px solid ${colors.border.secondary}`,
  },
};
