import React, { useState, useMemo, useCallback, useEffect } from 'react';
import {
  Building2, ChevronLeft, X, Trophy, Plus, Search, User, Loader,
} from 'lucide-react';
import { Button, Avatar } from '@shared/components/ui';
import { colors, spacing, borderRadius, typography, transitions } from '@shared/styles/theme';
import { supabase } from '@shared/lib/supabase';
import FormModal from '../../../components/FormModal';
import {
  FormField, TextInput, SelectInput, FormGrid, FormSection,
} from '../../../components/FormField';
import { generateCompetitionSlug } from '@shared/utils/slugs';

const WIZARD_STEPS = [
  { id: 1, name: 'Organization', description: 'Select organization' },
  { id: 2, name: 'Details', description: 'Name, city & season' },
  { id: 3, name: 'Contestants', description: 'Add past contestants' },
  { id: 4, name: 'Review', description: 'Confirm & create' },
];

const INITIAL_FORM = {
  organization_id: '',
  city_id: '',
  category_id: '',
  demographic_id: '',
  name: '',
  season: new Date().getFullYear(),
  number_of_winners: 5,
};

/**
 * Wizard for creating a legacy/historical competition record
 * for competitions that were hosted outside of EliteRank.
 */
export default function LegacyCompetitionWizard({
  isOpen,
  onClose,
  onCreate,
  loading,
  organizations,
  cities,
  categories,
  demographics,
}) {
  const [currentStep, setCurrentStep] = useState(1);
  const [formData, setFormData] = useState(INITIAL_FORM);
  const [contestants, setContestants] = useState([]);

  const resetAndClose = () => {
    setFormData(INITIAL_FORM);
    setContestants([]);
    setCurrentStep(1);
    onClose();
  };

  const updateField = (field, value) => {
    setFormData(prev => ({ ...prev, [field]: value }));
  };

  const seasonOptions = useMemo(() => {
    const years = [];
    for (let y = new Date().getFullYear(); y >= 2018; y--) {
      years.push({ value: String(y), label: String(y) });
    }
    return years;
  }, []);

  const cityOptions = useMemo(() =>
    cities.map(c => ({ value: c.id, label: `${c.name}, ${c.state}` })),
    [cities],
  );

  const categoryOptions = useMemo(() =>
    categories.map(c => ({ value: c.id, label: c.name })),
    [categories],
  );

  const demographicOptions = useMemo(() =>
    demographics.map(d => ({ value: d.id, label: d.label })),
    [demographics],
  );

  const autoGeneratedName = useMemo(() => {
    const org = organizations.find(o => o.id === formData.organization_id);
    const city = cities.find(c => c.id === formData.city_id);
    const demo = demographics.find(d => d.id === formData.demographic_id);
    if (!org || !city) return '';
    const isOpen = !demo || demo.slug === 'open';
    return isOpen ? `${org.name} ${city.name}` : `${org.name} ${city.name} - ${demo.label}`;
  }, [formData.organization_id, formData.city_id, formData.demographic_id, organizations, cities, demographics]);

  const canAdvance = useMemo(() => {
    if (currentStep === 1) return !!formData.organization_id;
    if (currentStep === 2) return !!(formData.city_id && formData.category_id && formData.demographic_id);
    return true;
  }, [currentStep, formData]);

  const canCreate = !!(formData.organization_id && formData.city_id && formData.category_id && formData.demographic_id);

  const handleSubmit = () => {
    if (currentStep < WIZARD_STEPS.length) {
      if (!canAdvance) return;
      setCurrentStep(prev => prev + 1);
    } else {
      if (!canCreate) return;
      onCreate({ ...formData, contestants });
    }
  };

  const addContestant = (profile) => {
    // Don't add duplicates
    if (contestants.some(c => c.profileId === profile.id)) return;
    if (contestants.length >= 20) return;

    setContestants(prev => [...prev, {
      profileId: profile.id,
      name: `${profile.first_name || ''} ${profile.last_name || ''}`.trim() || profile.email,
      email: profile.email,
      avatarUrl: profile.avatar_url,
      instagram: profile.instagram,
      city: profile.city,
      rank: prev.length + 1,
    }]);
  };

  const removeContestant = (profileId) => {
    setContestants(prev => {
      const filtered = prev.filter(c => c.profileId !== profileId);
      return filtered.map((c, i) => ({ ...c, rank: i + 1 }));
    });
  };

  const submitLabel = currentStep < WIZARD_STEPS.length
    ? 'Next'
    : loading ? 'Creating...' : 'Create Legacy Competition';

  const stepIndicator = (
    <div style={styles.stepBar}>
      {WIZARD_STEPS.map((step, index) => (
        <div key={step.id} style={styles.stepItem}>
          <div style={{
            ...styles.stepCircle,
            background: currentStep >= step.id ? colors.gold.primary : colors.background.elevated,
            color: currentStep >= step.id ? colors.text.inverse : colors.text.tertiary,
          }}>
            {step.id}
          </div>
          {index < WIZARD_STEPS.length - 1 && (
            <div style={{
              ...styles.stepLine,
              background: currentStep > step.id ? colors.gold.primary : colors.border.secondary,
            }} />
          )}
        </div>
      ))}
    </div>
  );

  return (
    <FormModal
      isOpen={isOpen}
      onClose={resetAndClose}
      title="Add Past Competition"
      subtitle={`Step ${currentStep} of ${WIZARD_STEPS.length}: ${WIZARD_STEPS[currentStep - 1].description}`}
      onSubmit={handleSubmit}
      submitLabel={submitLabel}
      loading={loading}
      size="lg"
    >
      {stepIndicator}

      {/* Step 1: Organization */}
      {currentStep === 1 && (
        <FormSection title="Select Organization" divider={false}>
          <div style={styles.orgList}>
            {organizations.map(org => (
              <button
                key={org.id}
                type="button"
                onClick={() => updateField('organization_id', org.id)}
                style={{
                  ...styles.orgCard,
                  borderColor: formData.organization_id === org.id ? colors.gold.primary : colors.border.primary,
                  background: formData.organization_id === org.id ? colors.gold.muted : colors.background.tertiary,
                }}
              >
                {org.logo_url ? (
                  <img src={org.logo_url} alt={org.name} style={styles.orgLogo} />
                ) : (
                  <div style={styles.orgLogoPlaceholder}>
                    <Building2 size={18} style={{ color: colors.text.tertiary }} />
                  </div>
                )}
                <div style={{ minWidth: 0 }}>
                  <p style={{ fontWeight: typography.fontWeight.medium, color: colors.text.primary, fontSize: typography.fontSize.sm }}>
                    {org.name}
                  </p>
                </div>
              </button>
            ))}
          </div>
        </FormSection>
      )}

      {/* Step 2: Details */}
      {currentStep === 2 && (
        <FormSection title="Competition Details" divider={false}>
          <FormGrid>
            <FormField label="City" required>
              <SelectInput
                value={formData.city_id}
                onChange={(e) => updateField('city_id', e.target.value)}
                options={cityOptions}
                placeholder="Select a city..."
              />
            </FormField>
            <FormField label="Season Year" required>
              <SelectInput
                value={String(formData.season)}
                onChange={(e) => updateField('season', parseInt(e.target.value))}
                options={seasonOptions}
              />
            </FormField>
          </FormGrid>
          <FormGrid>
            <FormField label="Category" required>
              <SelectInput
                value={formData.category_id}
                onChange={(e) => updateField('category_id', e.target.value)}
                options={categoryOptions}
                placeholder="Select a category..."
              />
            </FormField>
            <FormField label="Demographic" required>
              <SelectInput
                value={formData.demographic_id}
                onChange={(e) => updateField('demographic_id', e.target.value)}
                options={demographicOptions}
                placeholder="Select a demographic..."
              />
            </FormField>
          </FormGrid>
          <FormField
            label="Competition Name"
            description={formData.name
              ? 'Using custom name'
              : autoGeneratedName
                ? `Will auto-generate as: "${autoGeneratedName}"`
                : 'Leave blank to auto-generate'}
          >
            <TextInput
              value={formData.name}
              onChange={(e) => updateField('name', e.target.value)}
              placeholder={autoGeneratedName || 'e.g., Most Eligible Miami'}
            />
          </FormField>
        </FormSection>
      )}

      {/* Step 3: Contestants */}
      {currentStep === 3 && (
        <FormSection title="Past Contestants" divider={false}>
          <p style={{ fontSize: typography.fontSize.sm, color: colors.text.tertiary, margin: `0 0 ${spacing.md}` }}>
            Search and add up to 20 contestants in ranked order. The first added will be ranked #1.
          </p>
          <ProfileSearch
            onSelect={addContestant}
            excludeIds={contestants.map(c => c.profileId)}
            disabled={contestants.length >= 20}
          />
          {contestants.length > 0 && (
            <div style={{ display: 'flex', flexDirection: 'column', gap: spacing.sm, marginTop: spacing.lg }}>
              {contestants.map((c) => (
                <div key={c.profileId} style={styles.contestantRow}>
                  <div style={styles.rankBadge}>{c.rank}</div>
                  <Avatar name={c.name} size={36} avatarUrl={c.avatarUrl} />
                  <div style={{ flex: 1, minWidth: 0 }}>
                    <p style={{ fontWeight: typography.fontWeight.medium, color: colors.text.primary, fontSize: typography.fontSize.sm }}>{c.name}</p>
                    {c.instagram && (
                      <p style={{ color: colors.text.tertiary, fontSize: typography.fontSize.xs }}>@{c.instagram.replace('@', '')}</p>
                    )}
                  </div>
                  <button type="button" onClick={() => removeContestant(c.profileId)} style={styles.removeBtn}>
                    <X size={14} />
                  </button>
                </div>
              ))}
              <p style={{ fontSize: typography.fontSize.xs, color: colors.text.tertiary, textAlign: 'center', marginTop: spacing.xs }}>
                {contestants.length}/20 contestants added
              </p>
            </div>
          )}
        </FormSection>
      )}

      {/* Step 4: Review */}
      {currentStep === 4 && (
        <LegacyReviewStep
          formData={formData}
          contestants={contestants}
          organizations={organizations}
          cities={cities}
          categories={categories}
          demographics={demographics}
        />
      )}

      {currentStep > 1 && (
        <div style={styles.backButtonRow}>
          <Button
            variant="secondary"
            size="sm"
            icon={ChevronLeft}
            onClick={() => setCurrentStep(prev => Math.max(1, prev - 1))}
            type="button"
          >
            Back
          </Button>
        </div>
      )}
    </FormModal>
  );
}


/**
 * Inline profile search component for the contestants step.
 */
function ProfileSearch({ onSelect, excludeIds = [], disabled }) {
  const [query, setQuery] = useState('');
  const [results, setResults] = useState([]);
  const [searching, setSearching] = useState(false);

  const searchProfiles = useCallback(async (q) => {
    if (!q.trim() || !supabase) {
      setResults([]);
      return;
    }
    setSearching(true);
    try {
      const searchTerm = q.toLowerCase().trim();
      const { data } = await supabase
        .from('profiles')
        .select('id, email, first_name, last_name, avatar_url, instagram, city')
        .limit(100);

      const filtered = (data || []).filter(p => {
        if (excludeIds.includes(p.id)) return false;
        const firstName = (p.first_name || '').toLowerCase();
        const lastName = (p.last_name || '').toLowerCase();
        const fullName = `${firstName} ${lastName}`.toLowerCase();
        const email = (p.email || '').toLowerCase();
        const ig = (p.instagram || '').toLowerCase();
        return fullName.includes(searchTerm) || email.includes(searchTerm) || ig.includes(searchTerm);
      }).slice(0, 8);

      setResults(filtered);
    } catch (err) {
      console.error('Search error:', err);
    } finally {
      setSearching(false);
    }
  }, [excludeIds]);

  useEffect(() => {
    const timer = setTimeout(() => searchProfiles(query), 300);
    return () => clearTimeout(timer);
  }, [query, searchProfiles]);

  const getName = (p) => `${p.first_name || ''} ${p.last_name || ''}`.trim() || p.email;

  return (
    <div style={{ position: 'relative' }}>
      <div style={styles.searchBox}>
        <Search size={16} style={{ color: colors.text.muted, flexShrink: 0 }} />
        <input
          type="text"
          placeholder={disabled ? 'Maximum 20 contestants reached' : 'Search by name, email, or Instagram...'}
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          disabled={disabled}
          style={styles.searchInput}
        />
        {searching && <Loader size={14} style={{ animation: 'spin 1s linear infinite', color: colors.gold.primary }} />}
      </div>

      {results.length > 0 && (
        <div style={styles.dropdown}>
          {results.map(profile => (
            <button
              key={profile.id}
              type="button"
              onClick={() => {
                onSelect(profile);
                setQuery('');
                setResults([]);
              }}
              style={styles.dropdownItem}
              onMouseEnter={(e) => e.currentTarget.style.background = colors.background.elevated}
              onMouseLeave={(e) => e.currentTarget.style.background = 'transparent'}
            >
              <Avatar name={getName(profile)} size={32} avatarUrl={profile.avatar_url} />
              <div style={{ flex: 1, minWidth: 0 }}>
                <p style={{ fontWeight: typography.fontWeight.medium, color: colors.text.primary, fontSize: typography.fontSize.sm }}>
                  {getName(profile)}
                </p>
                <p style={{ color: colors.text.tertiary, fontSize: typography.fontSize.xs }}>
                  {profile.email}{profile.instagram && ` · @${profile.instagram.replace('@', '')}`}
                </p>
              </div>
              <Plus size={14} style={{ color: colors.gold.primary }} />
            </button>
          ))}
        </div>
      )}

      {query.trim() && !searching && results.length === 0 && (
        <div style={{ ...styles.dropdown, padding: spacing.lg, textAlign: 'center', color: colors.text.tertiary, fontSize: typography.fontSize.sm }}>
          <User size={20} style={{ marginBottom: spacing.xs, opacity: 0.5 }} />
          <p>No profiles found</p>
        </div>
      )}

      <style>{`@keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }`}</style>
    </div>
  );
}


function LegacyReviewStep({ formData, contestants, organizations, cities, categories, demographics }) {
  const selectedOrg = organizations.find(o => o.id === formData.organization_id);
  const selectedCity = cities.find(c => c.id === formData.city_id);
  const selectedCategory = categories.find(c => c.id === formData.category_id);
  const selectedDemographic = demographics.find(d => d.id === formData.demographic_id);
  const isOpenDemographic = selectedDemographic?.slug === 'open';

  const displayName = formData.name
    ? formData.name
    : selectedOrg && selectedCity
      ? isOpenDemographic || !selectedDemographic
        ? `${selectedOrg.name} ${selectedCity.name}`
        : `${selectedOrg.name} ${selectedCity.name} - ${selectedDemographic.label}`
      : 'Auto-generated';

  const rows = [
    { label: 'Organization', value: selectedOrg?.name || 'Not selected' },
    { label: 'Competition Name', value: displayName },
    { label: 'Location', value: selectedCity ? `${selectedCity.name}, ${selectedCity.state}` : 'Not selected' },
    { label: 'Category', value: selectedCategory?.name || 'Not selected' },
    { label: 'Demographic', value: selectedDemographic?.label || 'Not selected' },
    { label: 'Season', value: formData.season },
    { label: 'Contestants', value: `${contestants.length} added` },
    { label: 'Status', value: 'Completed (Legacy)' },
  ];

  return (
    <FormSection title="Review" divider={false}>
      <div style={styles.reviewGrid}>
        {rows.map(row => (
          <div key={row.label} style={styles.reviewRow}>
            <span style={styles.reviewLabel}>{row.label}</span>
            <span style={styles.reviewValue}>{row.value}</span>
          </div>
        ))}
      </div>

      {contestants.length > 0 && (
        <div style={{ marginTop: spacing.md }}>
          <p style={{ fontSize: typography.fontSize.xs, color: colors.text.tertiary, textTransform: 'uppercase', letterSpacing: '1px', marginBottom: spacing.sm }}>
            Contestants Preview
          </p>
          <div style={{ display: 'flex', gap: spacing.sm, flexWrap: 'wrap' }}>
            {contestants.map((c) => (
              <div key={c.profileId} style={{ display: 'flex', alignItems: 'center', gap: spacing.sm, padding: `${spacing.xs} ${spacing.sm}`, background: colors.background.tertiary, borderRadius: borderRadius.md }}>
                <span style={{ fontSize: typography.fontSize.xs, fontWeight: typography.fontWeight.bold, color: colors.gold.primary }}>{c.rank}</span>
                {c.avatarUrl ? (
                  <img src={c.avatarUrl} alt={c.name} style={{ width: 24, height: 24, borderRadius: borderRadius.full, objectFit: 'cover' }} />
                ) : (
                  <div style={{ width: 24, height: 24, borderRadius: borderRadius.full, background: colors.background.elevated, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                    <User size={12} style={{ color: colors.text.tertiary }} />
                  </div>
                )}
                <span style={{ fontSize: typography.fontSize.xs, color: colors.text.primary }}>{c.name}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      <p style={styles.footerNote}>
        This will create a completed competition record visible on the Explore page.
      </p>
    </FormSection>
  );
}


const styles = {
  stepBar: {
    display: 'flex',
    alignItems: 'center',
    gap: spacing[1],
    marginBottom: spacing.xl,
    padding: `${spacing.md} 0`,
    borderBottom: `1px solid ${colors.border.secondary}`,
  },
  stepItem: {
    display: 'flex',
    alignItems: 'center',
    flex: 1,
    gap: spacing[1],
  },
  stepCircle: {
    width: '24px',
    height: '24px',
    borderRadius: borderRadius.full,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: typography.fontSize.xs,
    fontWeight: typography.fontWeight.bold,
    flexShrink: 0,
  },
  stepLine: {
    flex: 1,
    height: '2px',
    borderRadius: '1px',
  },
  orgList: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.sm,
  },
  orgCard: {
    display: 'flex',
    alignItems: 'center',
    gap: spacing.md,
    padding: spacing.md,
    border: `1px solid ${colors.border.primary}`,
    borderRadius: borderRadius.md,
    cursor: 'pointer',
    textAlign: 'left',
    width: '100%',
    fontFamily: typography.fontFamily.sans,
    transition: transitions.colors,
  },
  orgLogo: {
    width: 36,
    height: 36,
    borderRadius: borderRadius.md,
    objectFit: 'cover',
    flexShrink: 0,
  },
  orgLogoPlaceholder: {
    width: 36,
    height: 36,
    borderRadius: borderRadius.md,
    background: colors.background.elevated,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  // Search
  searchBox: {
    display: 'flex',
    alignItems: 'center',
    gap: spacing.sm,
    padding: `${spacing.sm} ${spacing.md}`,
    background: colors.background.tertiary,
    border: `1px solid ${colors.border.primary}`,
    borderRadius: borderRadius.md,
  },
  searchInput: {
    flex: 1,
    background: 'none',
    border: 'none',
    outline: 'none',
    color: colors.text.primary,
    fontSize: typography.fontSize.sm,
    fontFamily: typography.fontFamily.sans,
  },
  dropdown: {
    position: 'absolute',
    top: '100%',
    left: 0,
    right: 0,
    marginTop: spacing.xs,
    background: colors.background.card,
    border: `1px solid ${colors.border.primary}`,
    borderRadius: borderRadius.md,
    boxShadow: '0 10px 40px rgba(0,0,0,0.5)',
    zIndex: 50,
    maxHeight: 250,
    overflow: 'auto',
  },
  dropdownItem: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    gap: spacing.sm,
    padding: spacing.sm,
    background: 'transparent',
    border: 'none',
    borderBottom: `1px solid ${colors.border.secondary}`,
    cursor: 'pointer',
    textAlign: 'left',
    fontFamily: typography.fontFamily.sans,
  },
  // Contestant list
  contestantRow: {
    display: 'flex',
    alignItems: 'center',
    gap: spacing.sm,
    padding: `${spacing.sm} ${spacing.md}`,
    background: colors.background.tertiary,
    borderRadius: borderRadius.md,
  },
  rankBadge: {
    width: 24,
    height: 24,
    borderRadius: borderRadius.full,
    background: colors.gold.muted,
    color: colors.gold.primary,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: typography.fontSize.xs,
    fontWeight: typography.fontWeight.bold,
    flexShrink: 0,
  },
  removeBtn: {
    background: 'transparent',
    border: 'none',
    color: colors.text.tertiary,
    cursor: 'pointer',
    padding: spacing.xs,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  // Review
  reviewGrid: {
    background: colors.background.tertiary,
    borderRadius: borderRadius.md,
    padding: spacing.md,
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.sm,
  },
  reviewRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: `${spacing[1]} 0`,
    borderBottom: `1px solid ${colors.border.secondary}`,
  },
  reviewLabel: {
    fontSize: typography.fontSize.xs,
    color: colors.text.tertiary,
    textTransform: 'uppercase',
    letterSpacing: typography.letterSpacing.wide,
  },
  reviewValue: {
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.medium,
    color: colors.text.primary,
  },
  footerNote: {
    fontSize: typography.fontSize.xs,
    color: colors.text.tertiary,
    textAlign: 'center',
    margin: 0,
    marginTop: spacing.md,
  },
  backButtonRow: {
    marginTop: spacing.lg,
    paddingTop: spacing.md,
    borderTop: `1px solid ${colors.border.secondary}`,
  },
};
